// priority: 1

StartupEvents.registry('sound_event', event => {
    event.create(`ftb:rift_weaver_boss`)
    event.create(`ftb:mystic_depths`)
    event.create("ftb:abyssal_archives_log1")
    event.create("ftb:abyssal_archives_log2")
    event.create("ftb:abyssal_archives_log3")
    event.create("ftb:abyssal_archives_log4")
    event.create("ftb:abyssal_archives_log5")
    event.create("ftb:abyssal_archives_log6")
    event.create("ftb:abyssal_archives_log7")
    event.create("ftb:abyssal_archives_log8")
    event.create("ftb:abyssal_archives_log9")
    event.create("ftb:abyssal_archives_log10")
    event.create("ftb:abyssal_archives_log11")
    event.create("ftb:abyssal_archives_log12")
    event.create("ftb:abyssal_archives_log13")
    event.create("ftb:abyssal_archives_log14")
    event.create("ftb:abyssal_archives_log15")
    event.create("ftb:abyssal_archives_log16")
    event.create("ftb:abyssal_archives_log17")
    event.create("ftb:abyssal_archives_log18")
    event.create("ftb:abyssal_archives_thankyou")
})